language: ruby

before_script:
 - bundle install 

script:
 - bundle exec jekyll build
 - bundle exec htmlproof ./_site

branches:
  only:
    - master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true