language: ruby

before_script:
 - bundle install 

script:
 - bundle exec jekyll build
 - bundle exec htmlproof ./_site --href-ignore "#/about,#/contact,#/resume"

branches:
  only:
    - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true