language: ruby
rvm:
- 2.1

before_script:
 - bundle install 

script:
 - bundle exec jekyll build
 - bundle exec htmlproof ./_site --href-ignore "#/about,#/contact,#/resume"

branches:
  only:
    - main

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true